[package]
name = "sea"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
scraper = "0.24.0"
url = "2.5.4"
lol_html = "2.6.0"
rand = "0.9.2"
